name: Format report
description: format bundle size report

inputs:
  masterBundleSizeMap: 
    required: true
    description: master bundle size map report
  bundleSizeStr:
    required: true
    description: current ref branch bundle size in formatted string
  bundleSizeMap:
    required: true
    description: current ref branch bundle size in map object

outputs:
  report: 
    description: output formatted message
    
runs:
  using: node16
  main: index.js

    